--------------------------------------------------------
--  Ref Constraints for Table CONVERSATIONS
--------------------------------------------------------

  ALTER TABLE "LUALARCON"."CONVERSATIONS" ADD CONSTRAINT "FK_CONV_INSCRIPCION" FOREIGN KEY ("ID_INSCRIPCION")
	  REFERENCES "LUALARCON"."INSCRIPCIONES" ("ID_INSCRIPCION") ENABLE;
  ALTER TABLE "LUALARCON"."CONVERSATIONS" ADD CONSTRAINT "FK_CONV_MISSION" FOREIGN KEY ("MISSION_ID")
	  REFERENCES "LUALARCON"."MISSIONS" ("MISSION_ID") ENABLE;
