--------------------------------------------------------
--  Ref Constraints for Table INSCRIPCIONES
--------------------------------------------------------

  ALTER TABLE "LUALARCON"."INSCRIPCIONES" ADD CONSTRAINT "FK_INS_ESTUDIANTE" FOREIGN KEY ("MATRICULA")
	  REFERENCES "LUALARCON"."ESTUDIANTES" ("MATRICULA") ENABLE;
  ALTER TABLE "LUALARCON"."INSCRIPCIONES" ADD CONSTRAINT "FK_INS_CURSO" FOREIGN KEY ("ID_CURSO")
	  REFERENCES "LUALARCON"."CURSOS" ("ID_CURSO") ENABLE;
  ALTER TABLE "LUALARCON"."INSCRIPCIONES" ADD CONSTRAINT "FK_INS_PERIODO" FOREIGN KEY ("ID_PERIODO")
	  REFERENCES "LUALARCON"."PERIODOS" ("ID_PERIODO") ENABLE;
  ALTER TABLE "LUALARCON"."INSCRIPCIONES" ADD CONSTRAINT "FK_INS_ACADEMICO" FOREIGN KEY ("ID_ACADEMICO")
	  REFERENCES "LUALARCON"."ACADEMICOS" ("ID_ACADEMICO") ENABLE;
