--------------------------------------------------------
--  Ref Constraints for Table USER_PROGRESS
--------------------------------------------------------

  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "FK_PROGRESS_INSCRIPCION" FOREIGN KEY ("ID_INSCRIPCION")
	  REFERENCES "LUALARCON"."INSCRIPCIONES" ("ID_INSCRIPCION") ENABLE;
  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "FK_PROGRESS_MISSION" FOREIGN KEY ("MISSION_ID")
	  REFERENCES "LUALARCON"."MISSIONS" ("MISSION_ID") ENABLE;
