-- Generated by Oracle SQL Developer REST Data Services 22.2.1.234.1810
-- Exported REST Definitions from ORDS Schema Version 26.1.0.r0791128
-- Schema: LUALARCON   Date: Mon Jun 01 15:11:58 CDT 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'LUALARCON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'api',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'chat',
      p_base_path      => '/chat/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.SET_MODULE_ORIGINS_ALLOWED(
      p_module_name     => 'chat',
      p_origins_allowed => 'http://localhost:5173');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'chat',
      p_pattern        => 'history/:conversation_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'chat',
      p_pattern        => 'history/:conversation_id',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT

    MESSAGE_ID,

    CONVERSATION_ID,

    SENDER,

    MESSAGE_TEXT,

    CORRECTION,

    SCORE,

    CREATED_AT

FROM CONVERSATION_MESSAGES

WHERE CONVERSATION_ID =
    :conversation_id

ORDER BY CREATED_AT'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'chat',
      p_pattern        => 'message',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'chat',
      p_pattern        => 'message',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '*',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    INSERT INTO CONVERSATION_MESSAGES (

        CONVERSATION_ID,

        SENDER,

        MESSAGE_TEXT,

        CORRECTION,

        CREATED_AT

    )

    VALUES (

        :conversation_id,

        :sender,

        :message_text,

        :correction,

        SYSTIMESTAMP

    );

    UPDATE CONVERSATIONS

    SET TOTAL_MESSAGES =
        NVL(TOTAL_MESSAGES, 0) + 1

    WHERE CONVERSATION_ID =
        :conversation_id;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;

    APEX_JSON.WRITE(
        ''success'',
        TRUE
    );

    APEX_JSON.CLOSE_OBJECT;

END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'chat',
      p_pattern        => 'start',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'chat',
      p_pattern        => 'start',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE

    V_CONVERSATION_ID NUMBER;

BEGIN

    INSERT INTO CONVERSATIONS (

        ID_INSCRIPCION,

        MISSION_ID,

        STARTED_AT,

        TOTAL_MESSAGES,

        STATUS,

        CREATED_AT

    )

    VALUES (

        :id_inscripcion,

        :mission_id,

        SYSTIMESTAMP,

        0,

        ''ACTIVE'',

        SYSTIMESTAMP

    )

    RETURNING CONVERSATION_ID
    INTO V_CONVERSATION_ID;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;

    APEX_JSON.WRITE(
        ''success'',
        TRUE
    );

    APEX_JSON.WRITE(
        ''conversationId'',
        V_CONVERSATION_ID
    );

    APEX_JSON.CLOSE_OBJECT;

END;'
      );


  COMMIT; 
END;