-- Generated by Oracle SQL Developer REST Data Services 22.2.1.234.1810
-- Exported REST Definitions from ORDS Schema Version 26.1.0.r0791128
-- Schema: LUALARCON   Date: Mon Jun 01 15:12:48 CDT 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'LUALARCON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'api',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'missions',
      p_base_path      => '/missions/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'missions',
      p_pattern        => 'course/:idCurso/:idinscripcion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'missions',
      p_pattern        => 'course/:idCurso/:idinscripcion',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    PKG_MISSIONS.GET_MISSIONS_BY_COURSE(
        p_id_curso => :idCurso,
        p_id_inscripcion=> :idinscripcion
    );

END;

'
      );


  COMMIT; 
END;