-- Generated by Oracle SQL Developer REST Data Services 22.2.1.234.1810
-- Exported REST Definitions from ORDS Schema Version 26.1.0.r0791128
-- Schema: LUALARCON   Date: Mon Jun 01 15:13:22 CDT 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'LUALARCON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'api',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'progress',
      p_base_path      => '/progress/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Modulo para agrupar los endpoints para rastrear el progreso del estudiante');      
  ORDS.SET_MODULE_ORIGINS_ALLOWED(
      p_module_name     => 'progress',
      p_origins_allowed => 'http://localhost:5173');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'add-xp',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'add-xp',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    ADD_XP_TO_PROGRESS(

        p_id_inscripcion => :id_inscripcion,

        p_mission_id => :mission_id,

        p_xp_earned => :xp_earned

    );

END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'complete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'complete',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    UPDATE USER_PROGRESS

    SET

        IS_COMPLETED = ''Y'',

        STATUS = ''COMPLETED'',

        PROGRESS_PERCENT = 100,

        COMPLETED_AT = SYSTIMESTAMP,

        UPDATED_AT = SYSTIMESTAMP

    WHERE ID_INSCRIPCION =
        :id_inscripcion

    AND MISSION_ID =
        :mission_id;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;

    APEX_JSON.WRITE(
        ''success'',
        TRUE
    );

    APEX_JSON.CLOSE_OBJECT;

END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'mission/:id_inscripcion/:mission_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'mission/:id_inscripcion/:mission_id',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT

    PROGRESS_PERCENT,

    TOTAL_XP_EARNED,

    TOTAL_MESSAGES,

    TOTAL_TIME_MINUTES,

    GRAMMAR_SCORE,

    PRONUNCIATION_SCORE,

    STATUS,

    IS_COMPLETED

FROM USER_PROGRESS

WHERE ID_INSCRIPCION = :id_inscripcion

AND MISSION_ID = :mission_id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'start',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'start',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE

    v_exists NUMBER;

BEGIN

    SELECT COUNT(*)

    INTO v_exists

    FROM USER_PROGRESS

    WHERE ID_INSCRIPCION = :id_inscripcion
    AND MISSION_ID = :mission_id;

    IF v_exists = 0 THEN

        INSERT INTO USER_PROGRESS (

            ID_INSCRIPCION,

            MISSION_ID,

            PROGRESS_PERCENT,

            IS_COMPLETED,

            TOTAL_XP_EARNED,

            TOTAL_MESSAGES,

            TOTAL_TIME_MINUTES,

            STATUS,

            CREATED_AT,

            UPDATED_AT

        )

        VALUES (

            :id_inscripcion,

            :mission_id,

            0,

            ''N'',

            0,

            0,

            0,

            ''IN_PROGRESS'',

            SYSTIMESTAMP,

            SYSTIMESTAMP
        );

    END IF;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;

    APEX_JSON.WRITE(
        ''success'',
        TRUE
    );

    APEX_JSON.CLOSE_OBJECT;

EXCEPTION

    WHEN OTHERS THEN

        ROLLBACK;

        APEX_JSON.OPEN_OBJECT;

        APEX_JSON.WRITE(
            ''success'',
            FALSE
        );

        APEX_JSON.WRITE(
            ''error'',
            SQLERRM
        );

        APEX_JSON.CLOSE_OBJECT;

END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'stats/:id_inscripcion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'stats/:id_inscripcion',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
    COUNT(*) AS TOTAL_MISSIONS,

    SUM(
        CASE
            WHEN IS_COMPLETED = ''Y''
            THEN 1
            ELSE 0
        END
    ) AS COMPLETED_MISSIONS,

    NVL(
        SUM(TOTAL_XP_EARNED),
        0
    ) AS TOTAL_XP,

    NVL(
        SUM(TOTAL_TIME_MINUTES),
        0
    ) AS TOTAL_TIME,

    ROUND(
        AVG(PROGRESS_PERCENT),
        0
    ) AS AVG_PROGRESS,

    ROUND(
        AVG(PRONUNCIATION_SCORE),
        1
    ) AS AVG_PRONUNCIATION,

    ROUND(
        AVG(GRAMMAR_SCORE),
        1
    ) AS AVG_GRAMMAR,

    FLOOR(
        NVL(
            SUM(TOTAL_XP_EARNED),
            0
        ) / 200
    ) + 1 AS "LEVEL",

    -- CORREGIDO: Se quitaron los par�ntesis exteriores innecesarios
    (
        FLOOR(
            NVL(
                SUM(TOTAL_XP_EARNED),
                0
            ) / 200
        ) + 1
    ) * 200 AS XP_NEXT_LEVEL

FROM USER_PROGRESS
WHERE ID_INSCRIPCION = :id_inscripcion'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'student/:id_inscripcion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'student/:id_inscripcion',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT

    COUNT(*) AS TOTAL_MISSIONS,

    SUM(
        CASE
            WHEN IS_COMPLETED = ''Y''
            THEN 1
            ELSE 0
        END
    ) AS COMPLETED_MISSIONS,

    SUM(TOTAL_XP_EARNED)
        AS TOTAL_XP,

    SUM(TOTAL_TIME_MINUTES)
        AS TOTAL_TIME,

    AVG(GRAMMAR_SCORE)
        AS AVG_GRAMMAR,

    AVG(PRONUNCIATION_SCORE)
        AS AVG_PRONUNCIATION

FROM USER_PROGRESS

WHERE ID_INSCRIPCION =
    :id_inscripcion'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'progress',
      p_pattern        => 'update',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'progress',
      p_pattern        => 'update',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    UPDATE USER_PROGRESS

    SET

        PROGRESS_PERCENT =
            :progress_percent,

        TOTAL_XP_EARNED =
            :total_xp_earned,

        TOTAL_MESSAGES =
            :total_messages,

        TOTAL_TIME_MINUTES =
            :total_time_minutes,

        GRAMMAR_SCORE =
            :grammar_score,

        PRONUNCIATION_SCORE =
            CASE
                WHEN :pronunciation_score IS NOT NULL
                THEN ROUND(
                    (NVL(PRONUNCIATION_SCORE, 0) + :pronunciation_score) / 2,
                    1
                )
                ELSE PRONUNCIATION_SCORE
            END,

        /*
        Mission completion
        */
        IS_COMPLETED =
            CASE
                WHEN :progress_percent >= 100
                THEN ''Y''
                ELSE IS_COMPLETED
            END,

        STATUS =
            CASE
                WHEN :progress_percent >= 100
                THEN ''COMPLETED''
                ELSE STATUS
            END,

        COMPLETED_AT =
            CASE
                WHEN :progress_percent >= 100
                THEN SYSTIMESTAMP
                ELSE COMPLETED_AT
            END,

        LAST_ACTIVITY =
            SYSTIMESTAMP,

        UPDATED_AT =
            SYSTIMESTAMP

    WHERE ID_INSCRIPCION =
        :id_inscripcion

    AND MISSION_ID =
        :mission_id;

    COMMIT;

    APEX_JSON.OPEN_OBJECT;

    APEX_JSON.WRITE(
        ''success'',
        TRUE
    );

    APEX_JSON.CLOSE_OBJECT;

END;'
      );


  COMMIT; 
END;