--------------------------------------------------------
--  DDL for Table ACADEMICOS
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."ACADEMICOS" 
   (	"ID_ACADEMICO" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"APELLIDOMATERNO" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"APELLIDOPATERNO" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"NOMBRE" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(512 BYTE) COLLATE "USING_NLS_COMP", 
	"ROL" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "LUALARCON"."ACADEMICOS" TO "EQUIPOCAA";
