--------------------------------------------------------
--  DDL for Table CONVERSATIONS
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."CONVERSATIONS" 
   (	"CONVERSATION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_INSCRIPCION" NUMBER, 
	"MISSION_ID" NUMBER, 
	"STARTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ENDED_AT" TIMESTAMP (6), 
	"TOTAL_MESSAGES" NUMBER DEFAULT 0, 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVE', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
