--------------------------------------------------------
--  DDL for Table CURSOS
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."CURSOS" 
   (	"ID_CURSO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOMBRE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPCION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NIVEL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIVO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
