--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."ESTUDIANTES" 
   (	"MATRICULA" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOPATERNO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOMATERNO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOMBRE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(512 BYTE) COLLATE "USING_NLS_COMP", 
	"CARRERA" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ROL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FOTO" BLOB, 
	"NIVEL_INGLES" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6), 
	"ULTIMO_ACCESO" TIMESTAMP (6), 
	"ESTADO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVO', 
	"XP" NUMBER DEFAULT 0, 
	"STREAK_DAYS" NUMBER DEFAULT 0, 
	"PREFERRED_LANGUAGE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_AI_SESSION" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("FOTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT DELETE ON "LUALARCON"."ESTUDIANTES" TO "EQUIPOCAA";
  GRANT INSERT ON "LUALARCON"."ESTUDIANTES" TO "EQUIPOCAA";
  GRANT SELECT ON "LUALARCON"."ESTUDIANTES" TO "EQUIPOCAA";
  GRANT UPDATE ON "LUALARCON"."ESTUDIANTES" TO "EQUIPOCAA";
