--------------------------------------------------------
--  DDL for Table INSCRIPCIONES
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."INSCRIPCIONES" 
   (	"ID_INSCRIPCION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MATRICULA" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_CURSO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_PERIODO" NUMBER(6,0), 
	"ID_ACADEMICO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FECHA_INSCRIPCION" DATE DEFAULT SYSDATE, 
	"ESTADO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVA', 
	"CALIFICACION_FINAL" NUMBER(5,2), 
	"APROBADO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
