--------------------------------------------------------
--  DDL for Table SPEAKING_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."SPEAKING_ANALYSIS" 
   (	"ANALYSIS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MESSAGE_ID" NUMBER, 
	"ORIGINAL_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"CORRECTED_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"GRAMMAR_FEEDBACK" CLOB COLLATE "USING_NLS_COMP", 
	"PRONUNCIATION_SCORE" NUMBER(5,2), 
	"FLUENCY_SCORE" NUMBER(5,2), 
	"VOCABULARY_SCORE" NUMBER(5,2), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("ORIGINAL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("CORRECTED_TEXT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("GRAMMAR_FEEDBACK") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
