--------------------------------------------------------
-- Archivo creado  - viernes-septiembre-25-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_PROGRESS
--------------------------------------------------------

  CREATE TABLE "LUALARCON"."USER_PROGRESS" 
   (	"PROGRESS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_INSCRIPCION" NUMBER, 
	"MISSION_ID" NUMBER, 
	"PROGRESS_PERCENT" NUMBER DEFAULT 0, 
	"IS_COMPLETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"TOTAL_XP_EARNED" NUMBER DEFAULT 0, 
	"LAST_ACTIVITY" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"TOTAL_MESSAGES" NUMBER DEFAULT 0, 
	"TOTAL_TIME_MINUTES" NUMBER DEFAULT 0, 
	"GRAMMAR_SCORE" NUMBER(5,2), 
	"PRONUNCIATION_SCORE" NUMBER(5,2), 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"COMPLETED_AT" TIMESTAMP (6), 
	"CURRENT_PHASE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'learning', 
	"LEARNING_COMPLETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"PRACTICE_COMPLETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"PRACTICE_SCORE" NUMBER(5,2) DEFAULT 0, 
	"ASSESSMENT_COMPLETED" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"PHASE_UPDATED_AT" TIMESTAMP (6), 
	"ACTIVITIES_ATTEMPTED" NUMBER DEFAULT 0, 
	"ACTIVITIES_CORRECT" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_PROGRESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUALARCON"."UK_PROGRESS" ON "LUALARCON"."USER_PROGRESS" ("ID_INSCRIPCION", "MISSION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER_PROGRESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LUALARCON"."PK_USER_PROGRESS" ON "LUALARCON"."USER_PROGRESS" ("PROGRESS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table USER_PROGRESS
--------------------------------------------------------

  ALTER TABLE "LUALARCON"."USER_PROGRESS" MODIFY ("PROGRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "LUALARCON"."USER_PROGRESS" MODIFY ("ID_INSCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "LUALARCON"."USER_PROGRESS" MODIFY ("MISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "PK_USER_PROGRESS" PRIMARY KEY ("PROGRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "UK_PROGRESS" UNIQUE ("ID_INSCRIPCION", "MISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_PROGRESS
--------------------------------------------------------

  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "FK_PROGRESS_INSCRIPCION" FOREIGN KEY ("ID_INSCRIPCION")
	  REFERENCES "LUALARCON"."INSCRIPCIONES" ("ID_INSCRIPCION") ENABLE;
  ALTER TABLE "LUALARCON"."USER_PROGRESS" ADD CONSTRAINT "FK_PROGRESS_MISSION" FOREIGN KEY ("MISSION_ID")
	  REFERENCES "LUALARCON"."MISSIONS" ("MISSION_ID") ENABLE;
